# Generated by Django 6.1.1 on 2026-09-14 00:54

import apps.complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_seed_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/', validators=[apps.complaints.models.validate_photo_size]),
        ),
    ]
